No linter errors, passes initial smoke tests

diff --git a/bin/include/n8mod_core_v1 b/bin/include/n8mod_core_v1
--- a/bin/include/n8mod_core_v1
+++ b/bin/include/n8mod_core_v1
@@ -22,10 +22,12 @@
 ##	Module copyright: At bottom of script.
 ##	Module history: At bottom of script. (Maintained separately from and/or in addition to, cloud-based version control.)
 
+## Bail if already loaded
+[[ "${N8MOD_CORE_V1_IS_LOADED:-}" == "1" ]] && return
 
 ## The following are defined here only for linter support.
-## They are required to be defined first by calling script.
-if [[ -z "${THIS_FILEPATH+x}" ]]; then
+## They are required to be defined first by the calling script, so should never get inside the if/fi.
+if [[ ! -v THIS_FILEPATH ]]; then
 	declare    THIS_FILEPATH  || :
 	declare    THIS_FILENAME  || :
 	declare    THIS_DIRPATH   || :
@@ -43,14 +45,14 @@ fi
 
 
 ##•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
-## For this module
-if [[ -z "${THIS_LIB_FILE_PATH_t5hpa+x}" ]]; then
+## Globals for this module. (The existence check is redundant but that's OK.)
+if [[ ! -v THIS_LIB_FILE_PATH_t5hpa ]]; then
 	## Constants
-	declare -r THIS_LIB_FILE_PATH_t5hpa="$(realpath -e "${BASH_SOURCE[0]}")"
-	declare -r THIS_LIB_FILE_NAME_t5hpa="$(basename "${THIS_LIB_FILE_PATH_t5hpa}")" #...: Replace with native bash function when ready.
-	declare -r THIS_LIB_DIR_PATH_t5hpa="$(dirname "${THIS_LIB_FILE_PATH_t5hpa}")" #.....: Replace with native bash function when ready.
-	declare -r SERIAL_DATETIME="$(date "+%Y%m%d-%H%M%S")"
-	declare -r RELAUNCH_SENTINELVAL="${THIS_LIB_FILE_NAME_t5hpa}_relaunch_4KQDYluNbzLQHwMwsWxgdk"  ## This funky string isn't for 'security' or uniqueness. It just a sentinel value that's unlikely as a user argument.
+	declare -gr THIS_LIB_FILE_PATH_t5hpa="$(realpath -e "${BASH_SOURCE[0]}")"
+	declare -gr THIS_LIB_FILE_NAME_t5hpa="$(basename "${THIS_LIB_FILE_PATH_t5hpa}")" #...: Replace with native bash function when ready.
+	declare -gr THIS_LIB_DIR_PATH_t5hpa="$(dirname "${THIS_LIB_FILE_PATH_t5hpa}")" #.....: Replace with native bash function when ready.
+	declare -gr SERIAL_DATETIME="$(date "+%Y%m%d-%H%M%S")"
+	declare -gr RELAUNCH_SENTINELVAL="${THIS_LIB_FILE_NAME_t5hpa}_relaunch_4KQDYluNbzLQHwMwsWxgdk"  ## This funky string isn't for 'security' or uniqueness. It just a sentinel value that's unlikely as a user argument.
 fi
 
 
@@ -64,15 +66,15 @@ fInit(){
 		## In this form, args:
 		##	Arg1: Literally "${RELAUNCH_SENTINELVAL}"
 		##	Arg2: Function name in calling parent script to launch with remaining arguments.
-		[[ -n "${2:-}" ]]                    || { echo -e "\nError in ${THIS_LIB_FILE_NAME_t5hpa}: A valid 'relaunch' sentinel value was passed as arg1, but no function name to branch to was passed as arg2.\n" ; return 1; }
-		declare -f "${2:-}" > /dev/null 2>&1 || { echo -e "\nError in ${THIS_LIB_FILE_NAME_t5hpa}: The function name passed as arg2 isn't defined in this environment: '${2:-}'.\n"                               ; return 1; }
+		[[ -n "${2:-}" ]]               || { echo -e "\nError in ${THIS_LIB_FILE_NAME_t5hpa}: A valid 'relaunch' sentinel value was passed as arg1, but no function name to branch to was passed as arg2.\n" ; return 1; }
+		declare -f "${2:-}" &>/dev/null || { echo -e "\nError in ${THIS_LIB_FILE_NAME_t5hpa}: The function name passed as arg2 isn't defined in this environment: '${2:-}'.\n"                               ; return 1; }
 		${2:-} "${3:-}" "${4:-}" "${5:-}" "${6:-}" "${7:-}" "${8:-}" "${9:-}" "${10:-}" "${11:-}" "${12:-}" "${13:-}" "${14:-}" "${15:-}" "${16:-}" "${17:-}" "${18:-}" "${19:-}" "${20:-}" "${21:-}" "${22:-}" "${23:-}" "${24:-}" "${25:-}" "${26:-}" "${27:-}" "${28:-}" "${29:-}" "${30:-}" "${31:-}" "${32:-}" "${33:-}" "${34:-}"
 
 	else
 
 		## The first and possibly/usually only entry point. Args are whatever the script needs.
 		## fMain() must exist in calling parent script.
-		declare -f "fMain" > /dev/null 2>&1 || { echo -e "\nError in ${THIS_LIB_FILE_NAME_t5hpa}: The function fMain() isn't defined in this environment: '${2:-}'.\n" ; return 1; }
+		declare -f "fMain" &>/dev/null || { echo -e "\nError in ${THIS_LIB_FILE_NAME_t5hpa}: The function fMain() isn't defined in this environment: '${2:-}'.\n" ; return 1; }
 		fMain  "${1:-}" "${2:-}" "${3:-}" "${4:-}" "${5:-}" "${6:-}" "${7:-}" "${8:-}" "${9:-}" "${10:-}" "${11:-}" "${12:-}" "${13:-}" "${14:-}" "${15:-}" "${16:-}" "${17:-}" "${18:-}" "${19:-}" "${20:-}" "${21:-}" "${22:-}" "${23:-}" "${24:-}" "${25:-}" "${26:-}" "${27:-}" "${28:-}" "${29:-}" "${30:-}" "${31:-}" "${32:-}"
 
 	fi
@@ -105,7 +107,7 @@ fGetOgUserHome(){
 	varName_s74rm=""
 	retVal="${HOME}"                                                                                       ; { [[ -n "${retVal}" ]] && [[ "${retVal,,}" != "/root" ]] && [[ -d "${retVal}" ]]; } && { varName_s74rm="${retVal}"; return 0; }
 	[[ -z "${userName_s74rm}" ]] && fGetOgUserName userName_s74rm
-	retVal="$(eval echo "~${userName_s74rm}")"                                                             ; { [[ -n "${retVal}" ]] && [[ "${retVal,,}" != "/root" ]] && [[ -d "${retVal}" ]]; } && { varName_s74rm="${retVal}"; return 0; }
+	retVal="$(getent passwd "${userName_s74rm}" | cut -d: -f6)"                                            ; { [[ -n "${retVal}" ]] && [[ "${retVal,,}" != "/root" ]] && [[ -d "${retVal}" ]]; } && { varName_s74rm="${retVal}"; return 0; }
 	retVal="$(getent passwd "${userName_s74rm:-${SUDO_USER:-${USER}}}" | cut -d: -f6 2>/dev/null || true)" ; { [[ -n "${retVal}" ]] && [[ "${retVal,,}" != "/root" ]] && [[ -d "${retVal}" ]]; } && { varName_s74rm="${retVal}"; return 0; }
 	retVal="/home/${userName_s74rm}"                                                                       ; { [[ -n "${retVal}" ]] && [[ "${retVal,,}" != "/root" ]] && [[ -d "${retVal}" ]]; } && { varName_s74rm="${retVal}"; return 0; }
 	retVal="${HOME}"                                                                                       ; { [[ -n "${retVal}" ]] && [[ -d "${retVal}" ]]; }                                   && { varName_s74rm="${retVal}"; return 0; }
@@ -132,15 +134,15 @@ fChainToFunc(){
 	else
 		## This case is [[ "${UID}" != "0" ]] && ((DO_CHAIN_SUDO)). Which means we need to relaunch the whole script (in a subshell) as sudo.
 		sudo echo "[ Relaunching as sudo ... ]"
-		sudo "${THIS_LIB_FILE_PATH_t5hpa}"  "${RELAUNCH_SENTINELVAL}"  "${chainFuncName}"  "${2:-}" "${3:-}" "${4:-}" "${5:-}" "${6:-}" "${7:-}" "${8:-}" "${9:-}" "${10:-}" "${11:-}" "${12:-}" "${13:-}" "${14:-}" "${15:-}" "${16:-}" "${17:-}" "${18:-}" "${19:-}" "${20:-}" "${21:-}" "${22:-}" "${23:-}" "${24:-}" "${25:-}" "${26:-}" "${27:-}" "${28:-}" "${29:-}" "${30:-}" "${31:-}" "${32:-}" "${33:-}"
+		sudo "${0}"  "${RELAUNCH_SENTINELVAL}"  "${chainFuncName}"  "${2:-}" "${3:-}" "${4:-}" "${5:-}" "${6:-}" "${7:-}" "${8:-}" "${9:-}" "${10:-}" "${11:-}" "${12:-}" "${13:-}" "${14:-}" "${15:-}" "${16:-}" "${17:-}" "${18:-}" "${19:-}" "${20:-}" "${21:-}" "${22:-}" "${23:-}" "${24:-}" "${25:-}" "${26:-}" "${27:-}" "${28:-}" "${29:-}" "${30:-}" "${31:-}" "${32:-}" "${33:-}"
 	fi
 }
 
 #•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
 ## Error-handling (minified but not obfuscated)
-declare -i _wasCleanupRun=0  ## Managed internally by this suite.
-declare -i _doExitOnThrow=0    ## Managed internally by this suite.
-declare -i _ErrVal=0         ## Set by this suite, but managed by calling functions. Think of it as an extended '$?' that doesn't immediately clear.
+declare -gi _wasCleanupRun=0  ## Managed internally by this suite.
+declare -gi _doExitOnThrow=0  ## Managed internally by this suite.
+declare -gi _ErrVal=0         ## Set by this suite, but managed by calling functions. Think of it as an extended '$?' that doesn't immediately clear.
 _fSingleExitPoint(){
 	local -r signal="${1:-}"
 	local -r lineNum="${2:-}"
@@ -167,12 +169,12 @@ _fSingleExitPoint(){
 		fCleanup  ## User cleanup
 	fi ;}
 _fTrap_Exit(){
-	if [[ "${_wasCleanupRun}" == "0" ]]; then  ## String compare is less to fail than integer
+	if [[ "${_wasCleanupRun:-}" == "0" ]]; then  ## String compare is less to fail than integer
 		_wasCleanupRun=1
 		_fSingleExitPoint "${1:-}" "${2:-}" "${3:-}" "${4:-}" "${5:-}" "${6:-}" "${7:-}" "${8:-}" "${9:-}" "${10:-}" "${11:-}" "${12:-}" "${13:-}" "${14:-}" "${15:-}" "${16:-}" "${17:-}" "${18:-}" "${19:-}" "${20:-}" "${21:-}" "${22:-}" "${23:-}" "${24:-}" "${25:-}" "${26:-}" "${27:-}" "${28:-}" "${29:-}" "${30:-}" "${31:-}" "${32:-}"
 	fi ;}
 _fTrap_Error(){
-	if [[ "${_wasCleanupRun}" == "0" ]]; then  ## String compare is less to fail than integer
+	if [[ "${_wasCleanupRun:-}" == "0" ]]; then  ## String compare is less to fail than integer
 		_wasCleanupRun=1
 		fEcho_ResetBlankCounter
 		_fSingleExitPoint "${1:-}" "${2:-}" "${3:-}" "${4:-}" "${5:-}" "${6:-}" "${7:-}" "${8:-}" "${9:-}" "${10:-}" "${11:-}" "${12:-}" "${13:-}" "${14:-}" "${15:-}" "${16:-}" "${17:-}" "${18:-}" "${19:-}" "${20:-}" "${21:-}" "${22:-}" "${23:-}" "${24:-}" "${25:-}" "${26:-}" "${27:-}" "${28:-}" "${29:-}" "${30:-}" "${31:-}" "${32:-}"
@@ -194,7 +196,7 @@ fThrowError(){
 	_ErrVal=1
 	{ ((_doExitOnThrow)) && exit 1; } || return 1; }
 fDefineTrap_Error_Fatal(){        :; _ErrVal=0; _doExitOnThrow=0; trap '_fTrap_Error         ERR    ${LINENO}  $?  $_' ERR; set -e; } ## Standard; exits script on any caught error; but 'set -e' has known inconsistencies catching or ignoring errors.
-fDefineTrap_Error_ExitOnThrow(){  :; _ErrVal=0; _doExitOnThrow=0; trap '_fTrap_Error         ERR    ${LINENO}  $?  $_' ERR; set +e; } ## Only exits script on fThrowError().
+fDefineTrap_Error_ExitOnThrow(){  :; _ErrVal=0; _doExitOnThrow=1; trap '_fTrap_Error         ERR    ${LINENO}  $?  $_' ERR; set -e; } ## Only exits script on fThrowError().
 fDefineTrap_Error_Soft(){         :; _ErrVal=0; _doExitOnThrow=0; trap '_fTrap_Error_Soft    ERR    ${LINENO}  $?  $_' ERR; set -e; } ## Returns error code of 1 on error.
 fDefineTrap_Error_Ignore(){       :; _ErrVal=0; _doExitOnThrow=0; trap '_fTrap_Error_Ignore  ERR    ${LINENO}  $?  $_' ERR; set +e; } ## Eats errors and returns true.
 trap '_fTrap_Error SIGHUP  ${LINENO} $? $_' SIGHUP
@@ -207,8 +209,8 @@ fDefineTrap_Error_Fatal                  ## ERR
 
 ##•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
 ## Echo-related (minified but not obfuscated)
-declare -i _wasLastEchoBlank=0
-declare -i _isEchoInRawInlineMode=0
+declare -gi _wasLastEchoBlank=0
+declare -gi _isEchoInRawInlineMode=0
 fEcho_ResetBlankCounter()     { _wasLastEchoBlank=0;      }
 fEcho_WasLastEchoBlank_Set()  { { [[ "${1}" == "1" ]] && _wasLastEchoBlank=1; } || _wasLastEchoBlank=0;  }
 fEcho_WasLastEchoBlank_Get()  { { ((_wasLastEchoBlank > 0)) && return 0; } || return 1; }
@@ -231,7 +233,13 @@ declare -i isSourced_t5hpa=0; [[ "${BASH_SOURCE[0]}" == "${0}" ]] || isSourced_t
 ((isSourced_t5hpa)) || { echo -e "\nError in $(basename "${BASH_SOURCE[0]}"): This script is meant to be 'sourced' from within another script.\n"; exit 1; }
 
 ## Flag this module as loaded.
-[[ -z "${N8MOD_CORE_V1_IS_LOADED+x}" ]] || declare -r N8MOD_CORE_V1_IS_LOADED=1
+[[ -v N8MOD_CORE_V1_IS_LOADED ]] || declare -gr N8MOD_CORE_V1_IS_LOADED=1
+
+## Validate this module interface as implemented by consuming script.
+[[ -n "${THIS_FILEPATH:-}" ]] || fThrowError "The constant 'THIS_FILEPATH' must be defined by the calling script, for this module to work."
+[[ -n "${THIS_FILENAME:-}" ]] || fThrowError "The constant 'THIS_FILENAME' must be defined by the calling script, for this module to work."
+[[ -n "${THIS_DIRPATH:-}"  ]] || fThrowError "The constant 'THIS_DIRPATH' must be defined by the calling script, for this module to work."
+[[ -n "${DO_CHAIN_SUDO:-}" ]] || fThrowError "The constant 'DO_CHAIN_SUDO' must be defined by the calling script, for this module to work."
 
 
 ##•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
diff --git a/bin/include/n8mod_string_v1 b/bin/include/n8mod_string_v1
--- a/bin/include/n8mod_string_v1
+++ b/bin/include/n8mod_string_v1
@@ -21,18 +21,29 @@
 ##	Module copyright: At bottom of script.
 ##	Module history: At bottom of script. (Maintained separately from and/or in addition to, cloud-based version control.)
 
+## Bail if already loaded
+[[ "${N8MOD_STRING_V1_IS_LOADED:-}" == "1" ]] && return
+
+## The following are defined here only for linter support.
+## They are required to be defined first by the calling script, so should never get inside the if/fi.
+#if [[ ! -v THIS_FILEPATH ]]; then
+#	declare    THIS_FILEPATH  || :
+#	declare    THIS_FILENAME  || :
+#	declare    THIS_DIRPATH   || :
+#fi
+
 #•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
-## For this module
-if [[ -z "${THIS_LIB_FILE_PATH_t5ht9+x}" ]]; then
+## Globals for this module. (The existence check is redundant but that's OK.)
+if [[ ! -x THIS_LIB_FILE_PATH_t5ht9 ]]; then
 	## Constants
-	declare -r THIS_LIB_FILE_PATH_t5ht9="$(realpath -e "${BASH_SOURCE[0]}")"
-	declare -r THIS_LIB_FILE_NAME_t5hte="$(basename "${THIS_LIB_FILE_PATH_t5ht9}")" #...: Replace with native bash function when ready.
-	declare -r THIS_LIB_DIR_PATH_t5hte="$(dirname "${THIS_LIB_FILE_PATH_t5ht9}")" #.....: Replace with native bash function when ready.
+	declare -gr THIS_LIB_FILE_PATH_t5ht9="$(realpath -e "${BASH_SOURCE[0]}")"
+	declare -gr THIS_LIB_FILE_NAME_t5hte="$(basename "${THIS_LIB_FILE_PATH_t5ht9}")" #...: Replace with native bash function when ready.
+	declare -gr THIS_LIB_DIR_PATH_t5hte="$(dirname "${THIS_LIB_FILE_PATH_t5ht9}")" #.....: Replace with native bash function when ready.
 fi
 
 ##•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
 ## String functions
-[[ -z "${BUILD_QUOTED_PARAMS_CHECK_PATTERN+x}" ]] && declare -r BUILD_QUOTED_PARAMS_CHECK_PATTERN=$'[][[:space:]|&;()<>`*?$!~{}\'\"#=,%@\\]'  ## If an arg has any of these in it, it needs quoting.
+[[ ! -v BUILD_QUOTED_PARAMS_CHECK_PATTERN ]] && declare -gr BUILD_QUOTED_PARAMS_CHECK_PATTERN=$'[][[:space:]|&;()<>`*?$!~{}\'\"#=,%@\\]'  ## If an arg has any of these in it, it needs quoting.
 fBuildQuotedParams(){
 	## Given up to 99 arguments following the parent variable to populate, populates that variable with a string, with the original arguments either as-is, or in quotes if they need it.
 	local -n varName_1mtkp9p=$1 ; shift || true  ## First argument is caller's variable to put results in. Remainging <= 99 variables are to put in quoted string.
@@ -56,10 +67,15 @@ declare -i isSourced_t5hte=0; [[ "${BASH_SOURCE[0]}" == "${0}" ]] || isSourced_t
 ((isSourced_t5hte)) || { echo -e "\nError in $(basename "${BASH_SOURCE[0]}"): This script is meant to be 'sourced' from within another script.\n"; exit 1; }
 
 ## Validate the assumption that required n8mod_core_v1 dependency is already loaded
-[[ "${N8MOD_CORE_V1_IS_LOADED}" == "1" ]] || { echo -e "\nError in $(basename "${BASH_SOURCE[0]}"): n8mod_core_v1 is not loaded yet. It's a core dependency that must be loaded first. All other dependencies auto-load.\n" ; exit 1; }
+[[ "${N8MOD_CORE_V1_IS_LOADED:-}" == "1" ]] || { echo -e "\nError in $(basename "${BASH_SOURCE[0]}"): n8mod_core_v1 is not loaded yet. It's a core dependency that must be loaded first. All other dependencies auto-load.\n" ; exit 1; }
+
+## Validate this module interface as implemented by consuming script.
+#[[ -n "${THIS_FILEPATH:-}" ]] || fThrowError "The constant 'THIS_FILEPATH' must be defined by the parent script, for this module to work."
+#[[ -n "${THIS_FILENAME:-}" ]] || fThrowError "The constant 'THIS_FILENAME' must be defined by the parent script, for this module to work."
+#[[ -n "${THIS_DIRPATH:-}"  ]] || fThrowError "The constant 'THIS_DIRPATH' must be defined by the parent script, for this module to work."
 
 ## Flag this module as loaded.
-[[ -n "${N8MOD_STRING_V1_IS_LOADED+x}" ]] || declare -r N8MOD_STRING_V1_IS_LOADED=1
+[[ -v N8MOD_STRING_V1_IS_LOADED ]] || declare -gr N8MOD_STRING_V1_IS_LOADED=1
 
 
 ##•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
