More modules better polished, CI/CD started

diff --git a/bin/include/n8mod_core_v1 b/bin/include/n8mod_core_v1
--- a/bin/include/n8mod_core_v1
+++ b/bin/include/n8mod_core_v1
@@ -85,15 +85,23 @@ fInit(){
 ##
 ## Core functions
 
+fIsFunction(){
+	[[ -n "${1:-}" ]]                ||  fThrowError "No function name specified."
+	declare -f "${1:-}" &>/dev/null  ||  return 1  ## Not a function
+	return 0  ## Is a function
+}
+
 ##•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
 ## Username and home
 fGetOgUserName(){
-	## Args:
-	local -n ptr_Output_s74rg=${1:-}  ## Arg <REQUIRED>: Nameref for return value.
-	## Validate
-	[[ -v ptr_Output_s74rg ]] || fThrowError "Calling function must pass a nameref to receive this function's output."
-	local    retVal=""
+	## Validate nameref args:
+	[[ -v 1 ]] || fThrowError "Calling function must pass a nameref to receive this function's output, as arg1."
+	## Gather args
+	local -n ptr_Output_s74rg=$1  ## ; shift || :  ## Arg <REQUIRED>: Nameref for return value.
+	## Init
+	local retVal=""
 	ptr_Output_s74rg=""
+	## Logic
 	retVal="${USER}"                         ; { [[ -n "${retVal}" ]] && [[ "${retVal,,}" != "root" ]]; } && { ptr_Output_s74rg="${retVal}"; return 0; }
 	retVal="${SUDO_USER}"                    ; { [[ -n "${retVal}" ]] && [[ "${retVal,,}" != "root" ]]; } && { ptr_Output_s74rg="${retVal}"; return 0; }
 	retVal="$(whoami  2>/dev/null || true)"  ; { [[ -n "${retVal}" ]] && [[ "${retVal,,}" != "root" ]]; } && { ptr_Output_s74rg="${retVal}"; return 0; }
@@ -104,13 +112,15 @@ fGetOgUserName(){
 	[[ -z "${retVal}" ]] && fThrowError  "Could not figure out username. This could be a bug [¢Яēᛏ]."  "${FUNCNAME[0]}"
 }
 fGetOgUserHome(){
-	## Args:
-	local -n ptr_Output_s74rm=${1:-}  ; shift || : ## Arg <REQUIRED>: Variable reference for result.
+	## Validate nameref args:
+	[[ -v 1 ]] || fThrowError "Calling function must pass a nameref to receive this function's output, as arg1."
+	## Gather args
+	local -n ptr_Output_s74rm=$1      ; shift || : ## Arg <REQUIRED>: Variable reference for result.
 	local    userName_s74rm="${2:-}"  ; shift || : ## Arg [optional]: Username. If blank will use fGetOguserName().
-	## Validate
-	[[ -v ptr_Output_s74rm ]] || fThrowError "Calling function must pass a nameref to receive this function's output."
+	## Init
 	local    retVal=""
 	ptr_Output_s74rm=""
+	## Logic
 	retVal="${HOME}"                                                                                       ; { [[ -n "${retVal}" ]] && [[ "${retVal,,}" != "/root" ]] && [[ -d "${retVal}" ]]; } && { ptr_Output_s74rm="${retVal}"; return 0; }
 	[[ -z "${userName_s74rm}" ]] && fGetOgUserName userName_s74rm
 	retVal="$(getent passwd "${userName_s74rm}" | cut -d: -f6)"                                            ; { [[ -n "${retVal}" ]] && [[ "${retVal,,}" != "/root" ]] && [[ -d "${retVal}" ]]; } && { ptr_Output_s74rm="${retVal}"; return 0; }
@@ -224,8 +234,11 @@ fEcho_WasLastEchoBlank_Get()  { { ((_wasLastEchoBlank > 0)) && return 0; } || re
 fEcho_IsInRawInlineMode_Set() { { [[ "${1:-}" == "1" ]] && _isEchoInRawInlineMode=1; } || { _isEchoInRawInlineMode=0; _wasLastEchoBlank=0; echo; }; }  ## Script it telling fEcho* that something is going to be echoing to the screen in non-linefeed mode without its knowledge. (E.g. "echo -n 'something: '".)
 fEcho_IsInRawInlineMode_Get() { { ((_isEchoInRawInlineMode)) && return 0; } || return 1; }
 fEcho_Clean_byref(){
-	local -n ptr_ToEcho_t5jf2=${1:-}
-	[[ -v ptr_ToEcho_t5jf2  ]] || fThrowError "Calling function must pass a nameref to supply the input value to this function."
+	## Validate nameref args:
+	[[ -v 1  ]] || fThrowError "Calling function must pass a nameref to supply the input value to this function, as arg1 (string to echo)."
+	## Gather args
+	local -n ptr_ToEcho_t5jf2=$1
+	## Logic
 	((_isEchoInRawInlineMode)) && fEcho_IsInRawInlineMode_Set 0
 	if [[ -n "${ptr_ToEcho_t5jf2}" ]]; then
 		echo -e "${ptr_ToEcho_t5jf2}"
@@ -250,11 +263,11 @@ declare -i isSourced_t5hpa=0; [[ "${BASH_SOURCE[0]}" == "${0}" ]] || isSourced_t
 ((isSourced_t5hpa)) || { echo -e "\nError in $(basename "${BASH_SOURCE[0]}"): This script is meant to be 'sourced' from within another script.\n"; exit 1; }
 
 ## Validate this module interface as implemented by consuming script.
-[[ -n "${THIS_FILEPATH:-}"            ]]  ||  fThrowError "The constant 'THIS_FILEPATH' must be defined by the calling script, for this module to work."
-[[ -n "${THIS_FILENAME:-}"            ]]  ||  fThrowError "The constant 'THIS_FILENAME' must be defined by the calling script, for this module to work."
-[[ -n "${THIS_DIRPATH:-}"             ]]  ||  fThrowError "The constant 'THIS_DIRPATH' must be defined by the calling script, for this module to work."
-[[ -n "${DO_CHAIN_SUDO:-}"            ]]  ||  fThrowError "The constant 'DO_CHAIN_SUDO' must be defined by the calling script, for this module to work."
-#declare -f  fLoadModule_v1  &>/dev/null  ||  fThrowError "The function 'fLoadModule_v1' must be defined by the calling script, for this module to work."
+[[ -n "${THIS_FILEPATH:-}"  ]]  ||  fThrowError "The constant 'THIS_FILEPATH' must be defined by the calling script, for this module to work."
+[[ -n "${THIS_FILENAME:-}"  ]]  ||  fThrowError "The constant 'THIS_FILENAME' must be defined by the calling script, for this module to work."
+[[ -n "${THIS_DIRPATH:-}"   ]]  ||  fThrowError "The constant 'THIS_DIRPATH' must be defined by the calling script, for this module to work."
+[[ -n "${DO_CHAIN_SUDO:-}"  ]]  ||  fThrowError "The constant 'DO_CHAIN_SUDO' must be defined by the calling script, for this module to work."
+#fIsFunction fLoadModule_v1     ||  fThrowError "The function 'fLoadModule_v1' must be defined by the calling script, for this module to work."
 
 ## Load dependency modules other than n8mod_code_v1.
 #[[ -v N8MOD_STRING_V1_IS_LOADED ]] || fLoadModule_v1  n8mod_string_v1
diff --git a/bin/include/n8mod_filesys_v1 b/bin/include/n8mod_filesys_v1
--- a/bin/include/n8mod_filesys_v1
+++ b/bin/include/n8mod_filesys_v1
@@ -46,43 +46,56 @@ fi
 ## Functions
 
 fDoesPathExist(){
-	## Purpose: Errors if path variable is empty or nonexistent.
-	## Arg:
-	local -n ptr_Path_t5jem=${1:-}  ## Arg: Caller nameref holding path.
-	[[ -v ptr_Path_t5jem  ]] || fThrowError "Calling function must pass a nameref to supply the input value to this function."
-	## Logic
-	[[ -n "${ptr_Path_t5jem}" ]] || fThrowError "No path specified."
-	[[ -e "${ptr_Path_t5jem}" ]] || return 1
-	return 0
-}
-
-fDoesDirExistWithContents(){
-	## Purpose: Errors if path variable is empty or nonexistent.
-	## Arg:
-	local -n ptr_Path_t5jer=${1:-}  ## Arg: Caller nameref holding path.
-	[[ -v ptr_Path_t5jer ]] || fThrowError "Calling function must pass a nameref to supply the input value to this function."
-	## Logic
-	[[ -n "${ptr_Path_t5jer}" ]]                        ||  fThrowError  "No directory specified."
-	[[ -d "${ptr_Path_t5jer}" ]]                        ||  return 1
-	[[ -n "$(ls -1A "${ptr_Path_t5jer%%/}/" 2>/dev/null || true)" ]] || return 1
+	##	Purpose: Basically the same as `[[ -e "${fsPath}" ]]`.
+	##	  No big benefit over that except this errors on empty.
+	[[ -n "${1:-}" ]] || fThrowError "No path specified."
+	[[ -e "${1:-}" ]] || return 1
 	return 0
 }
 
 fPathMustExist(){
-	## Purpose: Returns with 0 status if exists, 1 if null or not exist.
-	## Args:
-	local -n ptr_Path_t5jek=${1:-}  ## Arg: Caller nameref holding path.
-	[[ -v ptr_Path_t5jek ]] || fThrowError "Calling function must pass a nameref to supply the input value to this function."
-	## Logic
-	[[ -n "${ptr_Path_t5jek}" ]] || fThrowError "No path specified."
-	[[ -e "${ptr_Path_t5jek}" ]] || fThrowError "Specified path not found: '${ptr_Path_t5jek}'."
+	## Purpose: Like fDoesPathExist(), except errors if path not exist.
+	[[ -n "${1:-}" ]] || fThrowError "No path specified."
+	[[ -e "${1:-}" ]] || fThrowError "Specified path not found: '${1:-}'."
+}
+
+fDoesDirExistWithContents(){
+	##	Purpose: Success (0) if dir exists and has contents. Otherwise failure (>0). Only errors if nothing specified.
+	local checkPath="${1:-}"
+	[[ -n "${checkPath}" ]] || fThrowError "No folder path specified."
+	checkPath="${checkPath%%/}" ; { [[ -z "${checkPath}" ]] && checkPath='/'; } || checkPath="${checkPath}/"; readonly checkPath
+	[[ -d "${checkPath}" ]]                                  ||  return 1
+	[[ -n "$(ls -1A "${checkPath}" 2>/dev/null || true)" ]]  ||  return 1
+	return 0
+}
+
+fIsInPath(){
+	## Purpose: Success (0) if executable is found in $PATH. Otherwise failure (>0). Only errors if nothing specified.
+	[[ -n "${1:-}" ]]           ||  { fThrowError 'No executable specified to check for in $PATH.'  ; return 1; }
+	which "${1:-}" 2>/dev/null  ||  return 1
+	return 0
 }
 
 fMustBeInPath(){
-	local -r programToCheckForInPath="${1:-}"
-	[[ -n "${programToCheckForInPath}"                              ]]  ||  { fThrowError "Not program specified."                        ; return 1; }
-	[[ -n "$(which ${programToCheckForInPath} 2>/dev/null || true)" ]]  ||  { fThrowError "Not found in path: ${programToCheckForInPath}" ; return 1; }
+	## Purpose: Like fIsInPath, except errors if not.
+	[[ -n "${1:-}" ]]           ||  { fThrowError 'No executable specified to check for in $PATH.'  ; return 1; }
+	which "${1:-}" 2>/dev/null  ||  { fThrowError "Executable not found in \$PATH: ${1:-}"          ; return 1; }
 }
+
+fSafer_rm(){
+	local -r  rmDir="${1:-}"       ; shift || :  ## Arg <REQUIRED>: Dir to delete.
+	local -ri ignoreError=${1:-0}  ; shift || :  ## Arg [optional]: Ignore error on rm. [Default 0]
+	local -ri mustBeEmpty=${1:-1}  ; shift || :  ## Arg [optional]: Dir must be empty, or error. [Default 1]
+	[[ -n "${rmDir}"                  ]] || fThrowError  "No folder to delete specified."
+	[[ -d "${rmDir}"                  ]] || fThrowError  "Folder to delete doesn't seem to exist: '${rmDir}'."
+	[[    "${rmDir}"    == "/"        ]] && fThrowError  "I refuse to try to delete '/'!."
+	[[    "${rmDir%%/}" == "${HOME}"  ]] && fThrowError  "I refuse to try to delete '${HOME}'!."
+	{ ((mustBeEmpty)) && fDoesDirExistWithContents "${rmDir}"; }  &&  fThrowError  "Can't delete non-empty folder '${rmDir}/'."
+	fEcho "Removing folder '${rmDir}' ..."
+	if ((ignoreError)); then  rm -rf "${rmDir}" 2>/dev/null || true
+	else                      rm -rf "${rmDir}"
+	fi
+:;}
 
 
 
@@ -97,10 +110,10 @@ declare -i isSourced_t5jeb=0; [[ "${BASH_SOURCE[0]}" == "${0}" ]] || isSourced_t
 [[ "${N8MOD_CORE_V1_IS_LOADED:-}" == "1" ]] || { echo -e "\nError in $(basename "${BASH_SOURCE[0]}"): n8mod_core_v1 is not loaded yet. It's a core dependency that must be loaded first. All other dependencies auto-load.\n" ; exit 1; }
 
 ## Validate this module interface as implemented by consuming script.
-#[[ -n "${THIS_FILEPATH:-}"           ]]  ||  fThrowError "The constant 'THIS_FILEPATH' must be defined by the parent script, for this module to work."
-#[[ -n "${THIS_FILENAME:-}"           ]]  ||  fThrowError "The constant 'THIS_FILENAME' must be defined by the parent script, for this module to work."
-#[[ -n "${THIS_DIRPATH:-}"            ]]  ||  fThrowError "The constant 'THIS_DIRPATH' must be defined by the parent script, for this module to work."
-#declare -f  fLoadModule_v1  &>/dev/null  ||  fThrowError "The function 'fLoadModule_v1' must be defined by the calling script, for this module to work."
+#[[ -n "${THIS_FILEPATH:-}" ]]  ||  fThrowError "The constant 'THIS_FILEPATH' must be defined by the parent script, for this module to work."
+#[[ -n "${THIS_FILENAME:-}" ]]  ||  fThrowError "The constant 'THIS_FILENAME' must be defined by the parent script, for this module to work."
+#[[ -n "${THIS_DIRPATH:-}"  ]]  ||  fThrowError "The constant 'THIS_DIRPATH' must be defined by the parent script, for this module to work."
+#fIsFunction fLoadModule_v1     ||  fThrowError "The function 'fLoadModule_v1' must be defined by the calling script, for this module to work."
 
 ## Load dependency modules other than n8mod_code_v1.
 #[[ -v N8MOD_STRING_V1_IS_LOADED ]] || fLoadModule_v1  n8mod_string_v1
diff --git a/bin/include/n8mod_string_v1 b/bin/include/n8mod_string_v1
--- a/bin/include/n8mod_string_v1
+++ b/bin/include/n8mod_string_v1
@@ -42,16 +42,78 @@ if [[ ! -v THIS_LIB_FILE_PATH_t5jec ]]; then
 fi
 
 ##•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
-## Quoted params
+## Functions
+
+fGetStrMatchPos(){
+	##	Purpose: Returns 1-based index of position of first match. 0= no match.
+	##	Notes: Uses namerefs in so that any of the strings can be huge, with less performance hit.
+	## Validate nameref args:
+	[[ -v 1 ]]  ||  fThrowError "Calling function must pass a nameref to receive this function's integer output, as arg1."
+	[[ -v 2 ]]  ||  fThrowError "Calling function must pass a nameref to supply arg2 to this function (the source string)."
+	[[ -v 3 ]]  ||  fThrowError "Calling function must pass a nameref to supply arg3 to this function (the search substring)."
+	## Gather args
+	local -n ptr_Output_s74ht=$1         ; shift || :  ## Arg <REQUIRED>: Nameref: Int return value, 0=no match, >=1 position of start of firt match.
+	local -n ptr_SuperString_s74ht=$1    ; shift || :  ## Arg <REQUIRED>: Nameref: String: Main string to search in.
+	local -n ptr_FindSubString_s74ht=$1  ; shift || :  ## Arg <REQUIRED>: Nameref: String: String to find.
+	## Init
+	ptr_Output_s74ht=0
+	## Logic
+	{ [[ -z "${ptr_SuperString_s74ht}" ]] || [[ -z "${ptr_FindSubString_s74ht}" ]]; } && return 0
+	local -r testStr="${ptr_SuperString_s74ht%%"$ptr_FindSubString_s74ht"*}"
+	[[ "${testStr}" != "${ptr_SuperString_s74ht}" ]] && ptr_Output_s74ht=$((${#testStr}+1))
+:;}
+
+fSplitStr (){
+	##	Purpose: Split a string into left and right parts, on first occurrence of a given delimiter and specified scan direction.
+	##	Notes: Uses namerefs in so that any of the strings can be huge, with less performance hit.
+	## Validate nameref args:
+	[[ -v 1 ]] || fThrowError "Calling function must pass a nameref as arg1 to receive this function's 'left' output."
+	[[ -v 2 ]] || fThrowError "Calling function must pass a nameref as arg2 to receive this function's 'right' output."
+	[[ -v 3 ]] || fThrowError "Calling function must pass a nameref to supply arg3 as the input source string to this function (source string to split)."
+	## Gather args
+	local -n  ptr_output_LeftStr_s8hd0=$1       ; shift || :  ## Arg <REQUIRED>: Nameref: Str return value; left substring.
+	local -n  ptr_output_RightStr_s8hd0=$1      ; shift || :  ## Arg <REQUIRED>: Nameref: Str return value; right substring.
+	local -n  ptr_arg_SourcStr_s8hd0=$1         ; shift || :  ## Arg <REQUIRED>: Nameref: Str: Source nameref with string to parse.
+	local -r  delimStr="${1:- }"                ; shift || :  ## Arg [optional]: Str: The delimiter or substring to split on (default: space).
+	local -ri fromRight=${1:-0}                 ; shift || :  ## Arg [optional]: Int: 0 if scan from left (default), 1 if from right (e.g. for first '.' filename extension).
+	## Init
+	ptr_output_LeftStr_s8hd0=""
+	ptr_output_RightStr_s8hd0=""
+	## Conditions where we know nothing will be returned.
+	[[ -z "${ptr_arg_SourcStr_s8hd0}"  ]] && return 0
+	if ((fromRight)); then
+		## Conditions where we know that left will be empty, and right will == input.
+		[[ -z "${delimStr}"                                ]]  &&  { ptr_output_RightStr_s8hd0="${ptr_arg_SourcStr_s8hd0}"; return 0; }  ## Delimiter is empty.
+		[[     ${#delimStr} -ge ${#ptr_arg_SourcStr_s8hd0} ]]  &&  { ptr_output_RightStr_s8hd0="${ptr_arg_SourcStr_s8hd0}"; return 0; }  ## Delimiter is longer than source.
+		[[ "${ptr_arg_SourcStr_s8hd0}" != *"${delimStr}"*  ]]  &&  { ptr_output_RightStr_s8hd0="${ptr_arg_SourcStr_s8hd0}"; return 0; }  ## Delimiter not in source [technically a superset of previous test].
+		## Split on LAST match
+		ptr_output_LeftStr_s8hd0="${ptr_arg_SourcStr_s8hd0%"${delimStr}"*}"
+		ptr_output_RightStr_s8hd0="${ptr_arg_SourcStr_s8hd0##*"${delimStr}"}"
+	else
+		## Conditions where we know that right will be empty, and one left == input.
+		[[ -z "${delimStr}"                                ]]  &&  { ptr_output_LeftStr_s8hd0="${ptr_arg_SourcStr_s8hd0}"; return 0; }  ## Delimiter is empty.
+		[[     ${#delimStr} -ge ${#ptr_arg_SourcStr_s8hd0} ]]  &&  { ptr_output_LeftStr_s8hd0="${ptr_arg_SourcStr_s8hd0}"; return 0; }  ## Delimiter is longer than source.
+		[[ "${ptr_arg_SourcStr_s8hd0}" != *"${delimStr}"*  ]]  &&  { ptr_output_LeftStr_s8hd0="${ptr_arg_SourcStr_s8hd0}"; return 0; }  ## Delimiter not in source [technically a superset of previous test].
+		## Split on FIRST match
+		ptr_output_LeftStr_s8hd0="${ptr_arg_SourcStr_s8hd0%%"${delimStr}"*}"
+		ptr_output_RightStr_s8hd0="${ptr_arg_SourcStr_s8hd0#*"${delimStr}"}"
+	fi
+:;}
+
+##	Quoted params
+##		Purpose: Build a string from input parameters, with thing that need quoting, quoted, and thing that don't, not.
+##		Example: fBuildQuotedParams myReturnVar Now_is "the time" for    '{12}'   'it\'s'  "thing > 1" goto 10."
+##			"${myReturnVar}" == 'Now_is "the time" for "{12}" "it's" "thing > 1" goto 10."'
 if [[ ! -v BUILD_QUOTED_PARAMS_CHECK_PATTERN ]]; then
+	## Global constants
 	declare -gr  BUILD_QUOTED_PARAMS_CHECK_PATTERN=$'[][[:space:]|&;()<>`*?$!~{}\'\"#=,%@\\]'  ## If an arg has any of these in it, it needs quoting.
 	declare -gri BUILD_QUOTED_PARAMS_MAX_BLANK=10
 fi
 fBuildQuotedParams(){
-	## Arg 1
-	local -n ptr_Output_1mtkp9p=${1:-} ; shift || :  ## The caller variable to instert the return value into.
-	## Validate
-	[[ -v ptr_Output_1mtkp9p ]] || fThrowError "Calling function must pass a nameref to receive this function's output."
+	## Validate nameref args:
+	[[ -v 1 ]] || fThrowError "Calling function must pass a nameref to receive this function's output, as arg1."
+	## Gather args
+	local -n ptr_Output_1mtkp9p=1  # ; shift || :  ## The caller variable to instert the return value into.
 	## Init
 	ptr_Output_1mtkp9p=""
 	local retVal=""
@@ -85,10 +147,13 @@ declare -i isSourced_t5jec=0; [[ "${BASH_SOURCE[0]}" == "${0}" ]] || isSourced_t
 [[ "${N8MOD_CORE_V1_IS_LOADED:-}" == "1" ]] || { echo -e "\nError in $(basename "${BASH_SOURCE[0]}"): n8mod_core_v1 is not loaded yet. It's a core dependency that must be loaded first. All other dependencies auto-load.\n" ; exit 1; }
 
 ## Validate this module interface as implemented by consuming script.
-#[[ -n "${THIS_FILEPATH:-}"           ]]  ||  fThrowError "The constant 'THIS_FILEPATH' must be defined by the parent script, for this module to work."
-#[[ -n "${THIS_FILENAME:-}"           ]]  ||  fThrowError "The constant 'THIS_FILENAME' must be defined by the parent script, for this module to work."
-#[[ -n "${THIS_DIRPATH:-}"            ]]  ||  fThrowError "The constant 'THIS_DIRPATH' must be defined by the parent script, for this module to work."
-#declare -f  fLoadModule_v1  &>/dev/null  ||  fThrowError "The function 'fLoadModule_v1' must be defined by the calling script, for this module to work."
+#[[ -n "${THIS_FILEPATH:-}" ]]  ||  fThrowError "The constant 'THIS_FILEPATH' must be defined by the parent script, for this module to work."
+#[[ -n "${THIS_FILENAME:-}" ]]  ||  fThrowError "The constant 'THIS_FILENAME' must be defined by the parent script, for this module to work."
+#[[ -n "${THIS_DIRPATH:-}"  ]]  ||  fThrowError "The constant 'THIS_DIRPATH' must be defined by the parent script, for this module to work."
+#fIsFunction fLoadModule_v1     ||  fThrowError "The function 'fLoadModule_v1' must be defined by the calling script, for this module to work."
+
+## Load dependency modules other than n8mod_code_v1.
+#[[ -v N8MOD_NUMEBR_V1_IS_LOADED ]] || fLoadModule_v1  n8mod_number_v1
 
 ## Flag this module as loaded.
 [[ -v N8MOD_STRING_V1_IS_LOADED ]] || declare -gr N8MOD_STRING_V1_IS_LOADED=1
